version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  auth-server:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: ./compose/local/auth-server/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.local/.auth-server
    ports:
      - '8080:8080'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
      - ./compose/production/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
